language: c
git:
  submodules: true
env:
  global:
    - secure: H9lQEk76gGIi0TM9dGSZYmezr+8x4a4HQuwyJ1Z7wnWuW6diWtftfaim85AvjRpNnhpfz5ia6hmzLruOXbjDxCYp2RN9nhebBlGp9iYQsoyzZlTphWVNj0cGC9AIkxEtobswU3/A79FgnMhZxo5vSu4eotTgxo7nyiUaTuKB2nI=
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: g++
    env:
      - NODE_VERSION=12
  - os: osx
    osx_image: xcode7
    compiler: clang
    env:
      - NODE_VERSION=12
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
cache:
  npm: false
before_install:
- ./scripts/before_install.sh
install:
- ./scripts/install.sh
before_script:
- ulimit -c unlimited -S
- ulimit -a
script:
- ./scripts/test.sh
after_success:
- ./scripts/after_success.sh
